export const projects = [
  {
    id: "ai-radiologist",
    title: "AI-Radiologist",
    demo: "https://ai-radiologist.vercel.app/",
    ved:"https://drive.google.com/drive/folders/1riq5aVGt87GF9kAm3LzGFodv6VH8AhD_?usp=sharing",
    image: "/ai-radiologist.png", // الصورة الرئيسية
    screenshots: [
      "/screenshots/ai-radiologist-1.png",
      "/screenshots/ai-radiologist-2.png",
      "/screenshots/ai-radiologist-3.png",
      "/screenshots/ai-radiologist-4.png",
      "/screenshots/ai-radiologist-5.png",
      "/screenshots/ai-radiologist-6.png",
      "/screenshots/ai-radiologist-7.png",
      "/screenshots/ai-radiologist-8.png",
      "/screenshots/ai-radiologist-9.png",
      "/screenshots/ai-radiologist-10.png",

    ],
    description:
      "A responsive medical imaging platform that allows users to upload and analyze X-ray images using AI-powered diagnostics. It includes secure authentication, dynamic routing, user/admin dashboards, and full report management.",
    keyFeatures: [
      "Responsive web interface for X-ray analysis using AI.",
      "Dynamic routing and protected dashboards (login/register/dashboard).",
      "Upload, predict, and manage reports via RESTful APIs.",
    ],
    challenges: [
      "Handling file uploads securely.",
      "Maintaining auth state across components.",
      "Mobile optimization and responsive UI.",
    ],
    technologies: [
      "React.js",
      "React Router",
      "Axios",
      "React Hook Form",
      "Yup",
      "Context API",
      "Bootstrap 5",
      "SweetAlert2",
      "Framer Motion",
      "JWT",
    ],
    detailsUrl: "/projects/ai-radiologist",
  },
  {
    id: "ai-radiologist-admin",
    title: "AI-Radiologist Admin Dashboard",
    ved:"https://drive.google.com/drive/folders/18u6i-OpWDY6iGxmnaSj6O53BT40VfikH?usp=sharing",
    image: "/ai-radiologist.png",
    screenshots: [
      "/screenshots/ai-radiologist-admin-1.png",
      "/screenshots/ai-radiologist-admin-2.png",
      "/screenshots/ai-radiologist-admin-3.png",
      "/screenshots/ai-radiologist-admin-4.png",
    ],
    description:
      "A standalone admin dashboard for managing users, reports, and AI diagnostic models. Features include CRUD operations, role and status management, secure admin-only routes, and responsive design.",
    keyFeatures: [
      "Standalone admin dashboard to manage users, reports, and AI models.",
      "CRUD operations with role assignment and status toggling.",
      "Protected routes for managing sensitive data.",
    ],
    challenges: [
      "User permission handling.",
      "Secure admin-only routing.",
      "Responsive layout for tables and cards.",
    ],
    technologies: [
      "React.js",
      "React Router",
      "Axios",
      "React Hook Form",
      "Yup",
      "Context API",
      "JWT",
      "SweetAlert2",
      "React Toastify",
      "Bootstrap 5",
      "Framer Motion",
    ],
    detailsUrl: "/projects/ai-radiologist-admin",
  },
  {
  id: "ai-vora",
  title: "AI-Vora (AI Services Platform)",
  demo: "https://ai-vora.vercel.app/",
  image: "/ai-vora.png",
  screenshots: [
    "/screenshots/ai-vora.png",
  ],
  description:
    "AI-Vora is an intelligent web platform offering AI-powered business services including document analysis, image recognition, and automated reporting. it provides a seamless interface for clients to interact with advanced AI tools easily and securely.",
  keyFeatures: [
    "AI-based image and document analysis with instant report generation.",
    "User dashboard with history tracking and interactive visualizations.",
    "Role-based authentication and secure data management.",
    "Responsive, clean UI with smooth animations and dark/light modes.",
  ],
  challenges: [
    "Integrating AI models with real-time user input and API responses.",
    "Maintaining fast performance while handling large file uploads.",
    "Ensuring data privacy and secure backend communication.",
  ],
  technologies: [
    "React.js",
    "Next.js",
    "Tailwind CSS",
    "Redux Toolkit",
    "Axios",
    "Framer Motion",
    "React Hook Form",
    "Yup",
    "SweetAlert2",
  ],
  detailsUrl: "/projects/ai-vora",
},

  {
    id: "yusr",
title: "Yusr (Smart Rental Platform)",
demo: "https://yusr-rent.vercel.app/",
image: "/Logo-YSR.png",
screenshots: [
  "/screenshots/ysur_1.png",
    "/screenshots/ysur_2.png",
  "/screenshots/ysur_3.png",
  "/screenshots/ysur_4.png",
  "/screenshots/ysur_5.png",
  "/screenshots/ysur_7.png",
  "/screenshots/ysur_6.png",

],
description:
  "Yusr is a smart web platform that connects owners with renters, allowing users to list items for rent and request rentals for specific periods. The platform streamlines the rental process with secure authentication, real-time notifications, and a user-friendly interface.",
keyFeatures: [
  "Item listing system with images, location, and daily pricing.",
  "Rental request workflow with start/end date selection.",
  "Owner approval system with controlled contact information visibility.",
  "User profile dashboard to track sent and received rental requests.",
  "Real-time notifications for request status updates.",
  "Secure authentication and data handling using Supabase.",
  "Responsive UI with smooth animations and modern design.",
],
challenges: [
  "Designing a clear and fair rental request and approval flow.",
  "Managing real-time updates for rental requests and notifications.",
  "Ensuring data security while revealing contact details only after approval.",
  "Optimizing performance with image uploads and dynamic data fetching.",
],
technologies: [
  "React.js",
  "Next.js",
  "TypeScript",
  "Tailwind CSS",
  "Supabase (Auth, Database, Storage)",
  "Redux Toolkit",
  "Axios",
  "Framer Motion",
  "React Hook Form",
  "Yup",
  "SweetAlert2",
],
detailsUrl: "/projects/yusr",
},
{
    id: "elite-bank",
    title: "Elite Bank ",
    demo: "https://elite-bank-five.vercel.app/ar", // استبدله برابط الـ Vercel الفعلي الخاص بك
    image: "/Logo_EB.png", // الصورة الرئيسية من مشروعك
    screenshots: [
      "/screenshots/elite-bank-1.png",
      "/screenshots/elite-bank-2.png",
      "/screenshots/elite-bank-3.png",
    ],
    description:
      "A sophisticated digital banking landing page and platform featuring a high-end user experience. It includes interactive 3D bank cards, multi-language support (Arabic/English), dynamic account management sections, and a modern Bento Grid layout for banking services.",
    keyFeatures: [
      "Full Internationalization (i18n) support for Arabic (RTL) and English (LTR).",
      "Interactive 3D Credit Cards with continuous shine effects and hover animations.",
      "Modern Bento Grid layout for displaying different banking account types.",
      "Dynamic finance details pages (Auto, Real Estate, Personal) with tailored themes.",
      "Responsive navigation and localized routing using Next-Intl.",
    ],
    challenges: [
      "Managing complex RTL/LTR layout shifts and font consistencies.",
      "Implementing high-performance 3D CSS animations and continuous reflection effects.",
      "Ensuring strict TypeScript type safety across dynamic finance configurations.",
      "Optimizing heavy asset loading for a premium visual experience.",
    ],
    technologies: [
      "Next.js 16",
      "TypeScript",
      "Styled Components",
      "Tailwind CSS",
      "Framer Motion",
      "Next-Intl (i18n)",
      "Lucide Icons",
      "Turbopack",
    ],
    detailsUrl: "/projects/elite-bank",
  },

  {
    id: "tarf-ecommerce",
    title: "TARF (E-Commerce Web App)",
    demo:"https://tarf-shop.vercel.app/",
    ved: "https://drive.google.com/drive/folders/1fWH-A-KpLXpG1CT7iJsfmGJNgpb83alN?usp=sharing",
    image: "/tarf.png",
    screenshots: [
      "/screenshots/tarf-1.png",
      "/screenshots/tarf-2.png",
      "/screenshots/tarf-3.png",
      "/screenshots/tarf-4.png",
    ],
    description:
      "A modern online store built with Next.js and Tailwind CSS. Supports product listings, detailed product pages, shopping cart, and checkout with Redux state management for user sessions.",
    keyFeatures: [
      "Product listing, details, shopping cart, and checkout.",
      "Redux state management for cart and user sessions.",
      "SEO-friendly routing with Next.js.",
    ],
    challenges: [
      "Cart state persistence.",
      "API data integration for products and user flow.",
      "Optimized mobile-first layout.",
    ],
    technologies: [
      "Next.js",
      "Tailwind CSS",
      "Redux",
      "Axios",
      "REST APIs",
      "React Toastify",
      "React Hook Form",
      "Yup",
      "Context API",
    ],
    detailsUrl: "/projects/tarf-ecommerce",
  },
  {
    id: "movie-web-app",
    title: "Movie Web App",
    demo: "https://movie-web-app-lilac.vercel.app/",
    image: "/movie.png",
    screenshots: [
      "/screenshots/movie-web-app-1.png",
      "/screenshots/movie-web-app-2.png",
      "/screenshots/movie-web-app-3.png",
      "/screenshots/movie-web-app-4.png",
      "/screenshots/movie-web-app-5.png",
      "/screenshots/movie-web-app-6.png",
      "/screenshots/movie-web-app-7.png",
    ],
    description:
      "A movie browsing app featuring category filters, genre pages, and detailed movie information. Uses TMDB API with responsive carousels and dynamic routing.",
    keyFeatures: [
      "Movie browsing with category filters and genre pages.",
      "Detailed pages using TMDB API.",
      "Sliders and carousels built with Swiper.js.",
    ],
    challenges: [
      "Handling API rate limits and dynamic content.",
      "Responsive carousel design.",
      "Efficient data loading and pagination.",
    ],
    technologies: [
      "Next.js",
      "React.js",
      "Tailwind CSS",
      "Swiper.js",
      "Axios",
      "REST APIs",
    ],
    detailsUrl: "/projects/movie-web-app",
  },
   {
  id: "furnishop",
  title: "FurniShop (Furniture E-Commerce Site)",
  demo: "https://furnishop-two-delta.vercel.app/", // إن وجد رابط مباشر
  ved: "https://drive.google.com/drive/folders/1uDtjFFvcM3yg4PaNMhXj4c1ssYbLthNu?usp=sharing", // غيّره إذا كان عندك فيديو
  image: "/furnishop.png",
  screenshots: [
    "/screenshots/furniShop-1.png",
    "/screenshots/furniShop-2.png",

  ],
  description:
    "FurniShop is an online store specializing in furniture and home decor, allowing users to browse products smoothly through a well-organized, responsive slider that works seamlessly across all devices.",
  keyFeatures: [
    "Showcase furniture products in a clean and user-friendly layout.",
    "Responsive product slider for smooth navigation across devices.",
    "Well-structured product pages and visual browsing experience.",
  ],
  challenges: [
    "Creating a mobile-first responsive design.",
    "Implementing smooth and optimized slider components.",
    "Maintaining consistent UX across devices.",
  ],
  technologies: [
    "React.js",
    "React Router",
    "Tailwind CSS",
    "Framer Motion",
    "Swiper.js",
    "Axios",
  ],
  detailsUrl: "/projects/furnishop",
  },
];
